spring.application.name=finduhouse-backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finduhouse}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:finduhouse}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:finduhouse}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
